// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: achievements.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAchievements = `-- name: CreateAchievements :one
INSERT INTO achievements(
    achivements_name,
    icon_name,
    description,
    condition_type,
    condition_value
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, achivements_name, icon_name, description, condition_type, condition_value, created_at
`

type CreateAchievementsParams struct {
	AchivementsName string      `json:"achivements_name"`
	IconName        string      `json:"icon_name"`
	Description     string      `json:"description"`
	ConditionType   pgtype.Text `json:"condition_type"`
	ConditionValue  pgtype.Int4 `json:"condition_value"`
}

func (q *Queries) CreateAchievements(ctx context.Context, arg CreateAchievementsParams) (Achievement, error) {
	row := q.db.QueryRow(ctx, createAchievements,
		arg.AchivementsName,
		arg.IconName,
		arg.Description,
		arg.ConditionType,
		arg.ConditionValue,
	)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.AchivementsName,
		&i.IconName,
		&i.Description,
		&i.ConditionType,
		&i.ConditionValue,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAchievements = `-- name: DeleteAchievements :exec
DELETE FROM achievements
WHERE id = $1
`

func (q *Queries) DeleteAchievements(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAchievements, id)
	return err
}

const updateAchievements = `-- name: UpdateAchievements :one
UPDATE achievements
SET achivements_name = $2,icon_name = $3,description = $4,condition_type = $5,condition_value = $6
WHERE id = $1
RETURNING id, achivements_name, icon_name, description, condition_type, condition_value, created_at
`

type UpdateAchievementsParams struct {
	ID              int32       `json:"id"`
	AchivementsName string      `json:"achivements_name"`
	IconName        string      `json:"icon_name"`
	Description     string      `json:"description"`
	ConditionType   pgtype.Text `json:"condition_type"`
	ConditionValue  pgtype.Int4 `json:"condition_value"`
}

func (q *Queries) UpdateAchievements(ctx context.Context, arg UpdateAchievementsParams) (Achievement, error) {
	row := q.db.QueryRow(ctx, updateAchievements,
		arg.ID,
		arg.AchivementsName,
		arg.IconName,
		arg.Description,
		arg.ConditionType,
		arg.ConditionValue,
	)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.AchivementsName,
		&i.IconName,
		&i.Description,
		&i.ConditionType,
		&i.ConditionValue,
		&i.CreatedAt,
	)
	return i, err
}
