// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type News struct {
	ID               int32              `json:"id"`
	Title            string             `json:"title"`
	ShortDesсription string             `json:"short_desсription"`
	FullDesсription  string             `json:"full_desсription"`
	NewsDate         pgtype.Timestamp   `json:"news_date"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	CreatedBy        int32              `json:"created_by"`
}

type User struct {
	ID                 int32              `json:"id"`
	FullName           string             `json:"full_name"`
	Gender             pgtype.Text        `json:"gender"`
	DirectionVector    pgtype.Text        `json:"direction_vector"`
	StudyGroup         pgtype.Text        `json:"study_group"`
	Rating             pgtype.Int4        `json:"rating"`
	VisitedEventsCount pgtype.Int4        `json:"visited_events_count"`
	PhoneNumber        pgtype.Text        `json:"phone_number"`
	Telegram           string             `json:"telegram"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	JoinDate           pgtype.Timestamptz `json:"join_date"`
	Role               pgtype.Text        `json:"role"`
	TelegramID         pgtype.Int4        `json:"telegram_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}
