// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	CreateAchievements(ctx context.Context, arg CreateAchievementsParams) (Achievement, error)
	CreateNews(ctx context.Context, arg CreateNewsParams) (News, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAchievements(ctx context.Context, id int32) error
	DeleteNews(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetNews(ctx context.Context, id int32) (News, error)
	GetUser(ctx context.Context, id int32) (User, error)
	ListNews(ctx context.Context) ([]News, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateAchievements(ctx context.Context, arg UpdateAchievementsParams) (Achievement, error)
	UpdateNews(ctx context.Context, arg UpdateNewsParams) (News, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
