// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: achievements.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAchievements = `-- name: CreateAchievements :one
INSERT INTO achievements(
    achivements_name,
    icon_name,
    description,
    condition_type,
    condition_value
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, achivements_name, icon_name, description, condition_type, condition_value, created_at
`

type CreateAchievementsParams struct {
	AchivementsName string      `json:"achivements_name"`
	IconName        string      `json:"icon_name"`
	Description     string      `json:"description"`
	ConditionType   pgtype.Text `json:"condition_type"`
	ConditionValue  pgtype.Int4 `json:"condition_value"`
}

func (q *Queries) CreateAchievements(ctx context.Context, arg CreateAchievementsParams) (Achievement, error) {
	row := q.db.QueryRow(ctx, createAchievements,
		arg.AchivementsName,
		arg.IconName,
		arg.Description,
		arg.ConditionType,
		arg.ConditionValue,
	)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.AchivementsName,
		&i.IconName,
		&i.Description,
		&i.ConditionType,
		&i.ConditionValue,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAchievements = `-- name: DeleteAchievements :exec
DELETE FROM achievements
WHERE id = $1
`

func (q *Queries) DeleteAchievements(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAchievements, id)
	return err
}

const getAchievement = `-- name: GetAchievement :one
SELECT id, achivements_name, icon_name, description, condition_type, condition_value, created_at FROM achievements
WHERE id = $1
`

func (q *Queries) GetAchievement(ctx context.Context, id int32) (Achievement, error) {
	row := q.db.QueryRow(ctx, getAchievement, id)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.AchivementsName,
		&i.IconName,
		&i.Description,
		&i.ConditionType,
		&i.ConditionValue,
		&i.CreatedAt,
	)
	return i, err
}

const listAchievementsId = `-- name: ListAchievementsId :many
SELECT id, achivements_name, icon_name, description, condition_type, condition_value, created_at
FROM achievements
ORDER BY id ASC 
LIMIT $2
OFFSET $1
`

type ListAchievementsIdParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListAchievementsId(ctx context.Context, arg ListAchievementsIdParams) ([]Achievement, error) {
	rows, err := q.db.Query(ctx, listAchievementsId, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Achievement{}
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(
			&i.ID,
			&i.AchivementsName,
			&i.IconName,
			&i.Description,
			&i.ConditionType,
			&i.ConditionValue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
