// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByTelegramID = `-- name: GetUserByTelegramID :one
SELECT id, full_name, gender, direction_vector, study_group, rating, visited_events_count, phone_number, telegram, avatar_url, join_date, role, telegram_id FROM users
WHERE telegram_id = $1
LIMIT 1
`

func (q *Queries) GetUserByTelegramID(ctx context.Context, telegramID pgtype.Int4) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramID, telegramID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Gender,
		&i.DirectionVector,
		&i.StudyGroup,
		&i.Rating,
		&i.VisitedEventsCount,
		&i.PhoneNumber,
		&i.Telegram,
		&i.AvatarUrl,
		&i.JoinDate,
		&i.Role,
		&i.TelegramID,
	)
	return i, err
}

const getUserByTelegramUsername = `-- name: GetUserByTelegramUsername :one
SELECT id, full_name, gender, direction_vector, study_group, rating, visited_events_count, phone_number, telegram, avatar_url, join_date, role, telegram_id FROM users
WHERE telegram = $1
LIMIT 1
`

func (q *Queries) GetUserByTelegramUsername(ctx context.Context, telegram string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramUsername, telegram)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Gender,
		&i.DirectionVector,
		&i.StudyGroup,
		&i.Rating,
		&i.VisitedEventsCount,
		&i.PhoneNumber,
		&i.Telegram,
		&i.AvatarUrl,
		&i.JoinDate,
		&i.Role,
		&i.TelegramID,
	)
	return i, err
}

const updateUserTelegramData = `-- name: UpdateUserTelegramData :one
UPDATE users
SET 
    telegram = COALESCE($1, telegram),
    telegram_id = COALESCE($2, telegram_id),
    phone_number = COALESCE($3, phone_number)
WHERE id = $4
RETURNING id, full_name, gender, direction_vector, study_group, rating, visited_events_count, phone_number, telegram, avatar_url, join_date, role, telegram_id
`

type UpdateUserTelegramDataParams struct {
	Telegram    pgtype.Text `json:"telegram"`
	TelegramID  pgtype.Int4 `json:"telegram_id"`
	PhoneNumber pgtype.Text `json:"phone_number"`
	ID          int32       `json:"id"`
}

func (q *Queries) UpdateUserTelegramData(ctx context.Context, arg UpdateUserTelegramDataParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserTelegramData,
		arg.Telegram,
		arg.TelegramID,
		arg.PhoneNumber,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Gender,
		&i.DirectionVector,
		&i.StudyGroup,
		&i.Rating,
		&i.VisitedEventsCount,
		&i.PhoneNumber,
		&i.Telegram,
		&i.AvatarUrl,
		&i.JoinDate,
		&i.Role,
		&i.TelegramID,
	)
	return i, err
}
