// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    event_date,
    start_time,
    end_time,
    title,
    audience,
    weight,
    created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, event_date, start_time, end_time, title, audience, weight, created_by
`

type CreateEventParams struct {
	EventDate pgtype.Date `json:"event_date"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
	Title     pgtype.Text `json:"title"`
	Audience  pgtype.Text `json:"audience"`
	Weight    pgtype.Int4 `json:"weight"`
	CreatedBy int32       `json:"created_by"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.EventDate,
		arg.StartTime,
		arg.EndTime,
		arg.Title,
		arg.Audience,
		arg.Weight,
		arg.CreatedBy,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.EventDate,
		&i.StartTime,
		&i.EndTime,
		&i.Title,
		&i.Audience,
		&i.Weight,
		&i.CreatedBy,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, event_date, start_time, end_time, title, audience, weight, created_by FROM events
WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id int32) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.EventDate,
		&i.StartTime,
		&i.EndTime,
		&i.Title,
		&i.Audience,
		&i.Weight,
		&i.CreatedBy,
	)
	return i, err
}

const getEventsByUser = `-- name: GetEventsByUser :many
SELECT e.id, e.event_date, e.start_time, e.end_time, e.title, e.audience, e.weight, e.created_by FROM events e
WHERE e.created_by = $1
ORDER BY e.event_date DESC
LIMIT $3
OFFSET $2
`

type GetEventsByUserParams struct {
	CreatedBy int32 `json:"created_by"`
	Offset    int32 `json:"offset"`
	Limit     int32 `json:"limit"`
}

func (q *Queries) GetEventsByUser(ctx context.Context, arg GetEventsByUserParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsByUser, arg.CreatedBy, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.EventDate,
			&i.StartTime,
			&i.EndTime,
			&i.Title,
			&i.Audience,
			&i.Weight,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsDate = `-- name: ListEventsDate :many
SELECT id, event_date, start_time, end_time, title, audience, weight, created_by
FROM events
ORDER BY event_date ASC 
LIMIT $2
OFFSET $1
`

type ListEventsDateParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListEventsDate(ctx context.Context, arg ListEventsDateParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsDate, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.EventDate,
			&i.StartTime,
			&i.EndTime,
			&i.Title,
			&i.Audience,
			&i.Weight,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsId = `-- name: ListEventsId :many
SELECT id, event_date, start_time, end_time, title, audience, weight, created_by
FROM events
ORDER BY id ASC 
LIMIT $2
OFFSET $1
`

type ListEventsIdParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListEventsId(ctx context.Context, arg ListEventsIdParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsId, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.EventDate,
			&i.StartTime,
			&i.EndTime,
			&i.Title,
			&i.Audience,
			&i.Weight,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsTitle = `-- name: ListEventsTitle :many
SELECT id, event_date, start_time, end_time, title, audience, weight, created_by
FROM events
ORDER BY title ASC 
LIMIT $2
OFFSET $1
`

type ListEventsTitleParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListEventsTitle(ctx context.Context, arg ListEventsTitleParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsTitle, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.EventDate,
			&i.StartTime,
			&i.EndTime,
			&i.Title,
			&i.Audience,
			&i.Weight,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET 
    event_date = COALESCE($2, event_date),
    start_time = COALESCE($3, start_time),
    end_time = COALESCE($4, end_time),
    title = COALESCE($5, title),
    audience = COALESCE($6, audience),
    weight = COALESCE($7, weight)
WHERE id = $1
RETURNING id, event_date, start_time, end_time, title, audience, weight, created_by
`

type UpdateEventParams struct {
	ID        int32       `json:"id"`
	EventDate pgtype.Date `json:"event_date"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
	Title     pgtype.Text `json:"title"`
	Audience  pgtype.Text `json:"audience"`
	Weight    pgtype.Int4 `json:"weight"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.EventDate,
		arg.StartTime,
		arg.EndTime,
		arg.Title,
		arg.Audience,
		arg.Weight,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.EventDate,
		&i.StartTime,
		&i.EndTime,
		&i.Title,
		&i.Audience,
		&i.Weight,
		&i.CreatedBy,
	)
	return i, err
}
