// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Achievement struct {
	ID              int32              `json:"id"`
	AchivementsName string             `json:"achivements_name"`
	IconName        string             `json:"icon_name"`
	Description     string             `json:"description"`
	ConditionType   pgtype.Text        `json:"condition_type"`
	ConditionValue  pgtype.Int4        `json:"condition_value"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID        int32       `json:"id"`
	EventDate pgtype.Date `json:"event_date"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
	Title     pgtype.Text `json:"title"`
	Audience  pgtype.Text `json:"audience"`
	Weight    pgtype.Int4 `json:"weight"`
	CreatedBy int32       `json:"created_by"`
}

type News struct {
	ID               int32              `json:"id"`
	Title            string             `json:"title"`
	ShortDescription string             `json:"short_description"`
	FullDescription  string             `json:"full_description"`
	NewsDate         pgtype.Timestamp   `json:"news_date"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	CreatedBy        int32              `json:"created_by"`
}

type Notification struct {
	ID               int32              `json:"id"`
	UserID           int32              `json:"user_id"`
	EventID          int32              `json:"event_id"`
	NotificationDate pgtype.Timestamp   `json:"notification_date"`
	Sent             pgtype.Bool        `json:"sent"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

// User представляет пользователя системы
// @Description Модель пользователя
type User struct {
	ID                 int32              `json:"id"`
	FullName           string             `json:"full_name"`
	Gender             pgtype.Text        `json:"gender"`
	DirectionVector    pgtype.Text        `json:"direction_vector"`
	StudyGroup         pgtype.Text        `json:"study_group"`
	Rating             pgtype.Int4        `json:"rating"`
	VisitedEventsCount pgtype.Int4        `json:"visited_events_count"`
	PhoneNumber        pgtype.Text        `json:"phone_number"`
	Telegram           string             `json:"telegram"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	JoinDate           pgtype.Timestamptz `json:"join_date"`
	Role               pgtype.Text        `json:"role"`
	TelegramID         pgtype.Int4        `json:"telegram_id"`
}

type UserAchievement struct {
	ID            int32              `json:"id"`
	UserID        int32              `json:"user_id"`
	AchievementID int32              `json:"achievement_id"`
	AwardedAt     pgtype.Timestamptz `json:"awarded_at"`
	AwardedBy     int32              `json:"awarded_by"`
}

type UserEvent struct {
	ID       int32       `json:"id"`
	UserID   int32       `json:"user_id"`
	EventID  int32       `json:"event_id"`
	Attended pgtype.Bool `json:"attended"`
}
