// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: news.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNews = `-- name: CreateNews :one
INSERT INTO news(
    title,
    short_description,
    full_description,
    news_date,
    created_by
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, short_description, full_description, news_date, created_at, created_by
`

type CreateNewsParams struct {
	Title            string           `json:"title"`
	ShortDescription string           `json:"short_description"`
	FullDescription  string           `json:"full_description"`
	NewsDate         pgtype.Timestamp `json:"news_date"`
	CreatedBy        int32            `json:"created_by"`
}

func (q *Queries) CreateNews(ctx context.Context, arg CreateNewsParams) (News, error) {
	row := q.db.QueryRow(ctx, createNews,
		arg.Title,
		arg.ShortDescription,
		arg.FullDescription,
		arg.NewsDate,
		arg.CreatedBy,
	)
	var i News
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ShortDescription,
		&i.FullDescription,
		&i.NewsDate,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteNews = `-- name: DeleteNews :exec
DELETE FROM news
WHERE id = $1
`

func (q *Queries) DeleteNews(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteNews, id)
	return err
}

const getNews = `-- name: GetNews :one
SELECT id, title, short_description, full_description, news_date, created_at, created_by FROM news
WHERE id = $1
`

func (q *Queries) GetNews(ctx context.Context, id int32) (News, error) {
	row := q.db.QueryRow(ctx, getNews, id)
	var i News
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ShortDescription,
		&i.FullDescription,
		&i.NewsDate,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listNews = `-- name: ListNews :many
SELECT id, title, short_description, full_description, news_date, created_at, created_by FROM news
ORDER BY created_at DESC
`

func (q *Queries) ListNews(ctx context.Context) ([]News, error) {
	rows, err := q.db.Query(ctx, listNews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []News{}
	for rows.Next() {
		var i News
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ShortDescription,
			&i.FullDescription,
			&i.NewsDate,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNews = `-- name: UpdateNews :one
UPDATE news
SET title = $2, short_description=$3,full_description=$4,news_date=$5
WHERE id  = $1
RETURNING id, title, short_description, full_description, news_date, created_at, created_by
`

type UpdateNewsParams struct {
	ID               int32            `json:"id"`
	Title            string           `json:"title"`
	ShortDescription string           `json:"short_description"`
	FullDescription  string           `json:"full_description"`
	NewsDate         pgtype.Timestamp `json:"news_date"`
}

func (q *Queries) UpdateNews(ctx context.Context, arg UpdateNewsParams) (News, error) {
	row := q.db.QueryRow(ctx, updateNews,
		arg.ID,
		arg.Title,
		arg.ShortDescription,
		arg.FullDescription,
		arg.NewsDate,
	)
	var i News
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ShortDescription,
		&i.FullDescription,
		&i.NewsDate,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}
