// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    user_id,
    event_id,
    notification_type,
    message_text,
    status
)
VALUES ($1, $2, $3, $4, 'pending')
RETURNING id, user_id, event_id, notification_type, message_text, status, retry_count, last_error, created_at, queued_at, sent_at
`

type CreateNotificationParams struct {
	UserID           int32       `json:"user_id"`
	EventID          pgtype.Int4 `json:"event_id"`
	NotificationType string      `json:"notification_type"`
	MessageText      string      `json:"message_text"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.EventID,
		arg.NotificationType,
		arg.MessageText,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.NotificationType,
		&i.MessageText,
		&i.Status,
		&i.RetryCount,
		&i.LastError,
		&i.CreatedAt,
		&i.QueuedAt,
		&i.SentAt,
	)
	return i, err
}

const getPendingNotificationsBatch = `-- name: GetPendingNotificationsBatch :many
SELECT id, user_id, event_id, notification_type, message_text, status, retry_count, last_error, created_at, queued_at, sent_at
FROM notifications
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetPendingNotificationsBatch(ctx context.Context, limit int32) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getPendingNotificationsBatch, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.NotificationType,
			&i.MessageText,
			&i.Status,
			&i.RetryCount,
			&i.LastError,
			&i.CreatedAt,
			&i.QueuedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationFailed = `-- name: MarkNotificationFailed :one
UPDATE notifications
SET
    status = 'failed',
    retry_count = retry_count + 1,
    last_error = $2
WHERE id = $1
RETURNING id, user_id, event_id, notification_type, message_text, status, retry_count, last_error, created_at, queued_at, sent_at
`

type MarkNotificationFailedParams struct {
	ID        int32       `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkNotificationFailed(ctx context.Context, arg MarkNotificationFailedParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationFailed, arg.ID, arg.LastError)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.NotificationType,
		&i.MessageText,
		&i.Status,
		&i.RetryCount,
		&i.LastError,
		&i.CreatedAt,
		&i.QueuedAt,
		&i.SentAt,
	)
	return i, err
}

const markNotificationQueued = `-- name: MarkNotificationQueued :one
UPDATE notifications
SET
    status = 'queued',
    queued_at = NOW(),
    last_error = NULL
WHERE id = $1
  AND status = 'pending'
RETURNING id, user_id, event_id, notification_type, message_text, status, retry_count, last_error, created_at, queued_at, sent_at
`

func (q *Queries) MarkNotificationQueued(ctx context.Context, id int32) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationQueued, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.NotificationType,
		&i.MessageText,
		&i.Status,
		&i.RetryCount,
		&i.LastError,
		&i.CreatedAt,
		&i.QueuedAt,
		&i.SentAt,
	)
	return i, err
}

const markNotificationSent = `-- name: MarkNotificationSent :one
UPDATE notifications
SET
    status = 'sent',
    sent_at = NOW(),
    last_error = NULL
WHERE id = $1
  AND status IN ('queued', 'pending')
RETURNING id, user_id, event_id, notification_type, message_text, status, retry_count, last_error, created_at, queued_at, sent_at
`

func (q *Queries) MarkNotificationSent(ctx context.Context, id int32) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationSent, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.NotificationType,
		&i.MessageText,
		&i.Status,
		&i.RetryCount,
		&i.LastError,
		&i.CreatedAt,
		&i.QueuedAt,
		&i.SentAt,
	)
	return i, err
}

const retryFailedNotification = `-- name: RetryFailedNotification :one
UPDATE notifications
SET
    status = 'pending',
    last_error = NULL
WHERE id = $1
  AND status = 'failed'
RETURNING id, user_id, event_id, notification_type, message_text, status, retry_count, last_error, created_at, queued_at, sent_at
`

func (q *Queries) RetryFailedNotification(ctx context.Context, id int32) (Notification, error) {
	row := q.db.QueryRow(ctx, retryFailedNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.NotificationType,
		&i.MessageText,
		&i.Status,
		&i.RetryCount,
		&i.LastError,
		&i.CreatedAt,
		&i.QueuedAt,
		&i.SentAt,
	)
	return i, err
}
