// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddUserAchievements(ctx context.Context, arg AddUserAchievementsParams) error
	AddUserEvent(ctx context.Context, arg AddUserEventParams) error
	CreateAchievements(ctx context.Context, arg CreateAchievementsParams) (Achievement, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateNews(ctx context.Context, arg CreateNewsParams) (News, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAchievements(ctx context.Context, id int32) error
	DeleteEvent(ctx context.Context, id int32) error
	DeleteNews(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) (int64, error)
	GetAchievement(ctx context.Context, id int32) (Achievement, error)
	GetEvent(ctx context.Context, id int32) (Event, error)
	GetEventsByUser(ctx context.Context, arg GetEventsByUserParams) ([]Event, error)
	GetNews(ctx context.Context, id int32) (News, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserAchievementsByUserID(ctx context.Context, arg GetUserAchievementsByUserIDParams) ([]Achievement, error)
	GetUserByTelegramID(ctx context.Context, telegramID pgtype.Int4) (User, error)
	GetUserByTelegramUsername(ctx context.Context, telegram string) (User, error)
	GetUserEventsByUserID(ctx context.Context, arg GetUserEventsByUserIDParams) ([]Event, error)
	ListAchievementsId(ctx context.Context, arg ListAchievementsIdParams) ([]Achievement, error)
	ListEventsByFilter(ctx context.Context, arg ListEventsByFilterParams) ([]Event, error)
	ListEventsDate(ctx context.Context, arg ListEventsDateParams) ([]Event, error)
	ListEventsId(ctx context.Context, arg ListEventsIdParams) ([]Event, error)
	ListEventsTitle(ctx context.Context, arg ListEventsTitleParams) ([]Event, error)
	ListNews(ctx context.Context) ([]News, error)
	ListUsersSorted(ctx context.Context, arg ListUsersSortedParams) ([]User, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateNews(ctx context.Context, arg UpdateNewsParams) (News, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserTelegramData(ctx context.Context, arg UpdateUserTelegramDataParams) (User, error)
}

var _ Querier = (*Queries)(nil)
