// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_events.sql

package repository

import (
	"context"
)

const addUserEvent = `-- name: AddUserEvent :exec
INSERT INTO user_events (
    user_id,
    event_id
)
VALUES ($1, $2)
ON CONFLICT (user_id, event_id) DO NOTHING
`

type AddUserEventParams struct {
	UserID  int32 `json:"user_id"`
	EventID int32 `json:"event_id"`
}

func (q *Queries) AddUserEvent(ctx context.Context, arg AddUserEventParams) error {
	_, err := q.db.Exec(ctx, addUserEvent, arg.UserID, arg.EventID)
	return err
}

const getUserEventsByUserID = `-- name: GetUserEventsByUserID :many
SELECT e.id, e.event_date, e.start_time, e.end_time, e.title, e.audience, e.weight, e.created_by
FROM events e
JOIN user_events ue ON ue.event_id = e.id
WHERE ue.user_id = $1
ORDER BY e.event_date DESC
LIMIT $3
OFFSET $2
`

type GetUserEventsByUserIDParams struct {
	UserID int32 `json:"user_id"`
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) GetUserEventsByUserID(ctx context.Context, arg GetUserEventsByUserIDParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getUserEventsByUserID, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.EventDate,
			&i.StartTime,
			&i.EndTime,
			&i.Title,
			&i.Audience,
			&i.Weight,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
