// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    full_name,
    gender,
    direction_vector,
    study_group,
    rating,
    visited_events_count,
    phone_number,
    telegram,
    avatar_url,
    telegram_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, full_name, gender, direction_vector, study_group, rating, visited_events_count, phone_number, telegram, avatar_url, join_date, role, telegram_id, created_at, updated_at
`

type CreateUserParams struct {
	FullName           string      `json:"full_name"`
	Gender             pgtype.Text `json:"gender"`
	DirectionVector    pgtype.Text `json:"direction_vector"`
	StudyGroup         pgtype.Text `json:"study_group"`
	Rating             pgtype.Int4 `json:"rating"`
	VisitedEventsCount pgtype.Int4 `json:"visited_events_count"`
	PhoneNumber        pgtype.Text `json:"phone_number"`
	Telegram           string      `json:"telegram"`
	AvatarUrl          pgtype.Text `json:"avatar_url"`
	TelegramID         pgtype.Int4 `json:"telegram_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FullName,
		arg.Gender,
		arg.DirectionVector,
		arg.StudyGroup,
		arg.Rating,
		arg.VisitedEventsCount,
		arg.PhoneNumber,
		arg.Telegram,
		arg.AvatarUrl,
		arg.TelegramID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Gender,
		&i.DirectionVector,
		&i.StudyGroup,
		&i.Rating,
		&i.VisitedEventsCount,
		&i.PhoneNumber,
		&i.Telegram,
		&i.AvatarUrl,
		&i.JoinDate,
		&i.Role,
		&i.TelegramID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, full_name, gender, direction_vector, study_group, rating, visited_events_count, phone_number, telegram, avatar_url, join_date, role, telegram_id, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Gender,
		&i.DirectionVector,
		&i.StudyGroup,
		&i.Rating,
		&i.VisitedEventsCount,
		&i.PhoneNumber,
		&i.Telegram,
		&i.AvatarUrl,
		&i.JoinDate,
		&i.Role,
		&i.TelegramID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, full_name, gender, direction_vector, study_group, rating, visited_events_count, phone_number, telegram, avatar_url, join_date, role, telegram_id, created_at, updated_at FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Gender,
			&i.DirectionVector,
			&i.StudyGroup,
			&i.Rating,
			&i.VisitedEventsCount,
			&i.PhoneNumber,
			&i.Telegram,
			&i.AvatarUrl,
			&i.JoinDate,
			&i.Role,
			&i.TelegramID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET full_name=$2, gender=$3, direction_vector=$4,study_group=$5,rating=$6,visited_events_count=$7,phone_number=$8,telegram=$9,avatar_url=$10,role=$11,telegram_id=$12
WHERE id = $1
RETURNING id, full_name, gender, direction_vector, study_group, rating, visited_events_count, phone_number, telegram, avatar_url, join_date, role, telegram_id, created_at, updated_at
`

type UpdateUserParams struct {
	ID                 int32       `json:"id"`
	FullName           string      `json:"full_name"`
	Gender             pgtype.Text `json:"gender"`
	DirectionVector    pgtype.Text `json:"direction_vector"`
	StudyGroup         pgtype.Text `json:"study_group"`
	Rating             pgtype.Int4 `json:"rating"`
	VisitedEventsCount pgtype.Int4 `json:"visited_events_count"`
	PhoneNumber        pgtype.Text `json:"phone_number"`
	Telegram           string      `json:"telegram"`
	AvatarUrl          pgtype.Text `json:"avatar_url"`
	Role               pgtype.Text `json:"role"`
	TelegramID         pgtype.Int4 `json:"telegram_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.Gender,
		arg.DirectionVector,
		arg.StudyGroup,
		arg.Rating,
		arg.VisitedEventsCount,
		arg.PhoneNumber,
		arg.Telegram,
		arg.AvatarUrl,
		arg.Role,
		arg.TelegramID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Gender,
		&i.DirectionVector,
		&i.StudyGroup,
		&i.Rating,
		&i.VisitedEventsCount,
		&i.PhoneNumber,
		&i.Telegram,
		&i.AvatarUrl,
		&i.JoinDate,
		&i.Role,
		&i.TelegramID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
