// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    full_name,
    gender,
    direction_vector,
    study_group,
    rating,
    visited_events_count,
    phone_number,
    telegram,
    avatar_url
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, full_name, gender, direction_vector, study_group, rating, visited_events_count, phone_number, telegram, avatar_url, join_date, role, telegram_id
`

type CreateUserParams struct {
	FullName           string      `json:"full_name"`
	Gender             pgtype.Text `json:"gender"`
	DirectionVector    pgtype.Text `json:"direction_vector"`
	StudyGroup         pgtype.Text `json:"study_group"`
	Rating             pgtype.Int4 `json:"rating"`
	VisitedEventsCount pgtype.Int4 `json:"visited_events_count"`
	PhoneNumber        pgtype.Text `json:"phone_number"`
	Telegram           string      `json:"telegram"`
	AvatarUrl          pgtype.Text `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FullName,
		arg.Gender,
		arg.DirectionVector,
		arg.StudyGroup,
		arg.Rating,
		arg.VisitedEventsCount,
		arg.PhoneNumber,
		arg.Telegram,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Gender,
		&i.DirectionVector,
		&i.StudyGroup,
		&i.Rating,
		&i.VisitedEventsCount,
		&i.PhoneNumber,
		&i.Telegram,
		&i.AvatarUrl,
		&i.JoinDate,
		&i.Role,
		&i.TelegramID,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, full_name, gender, direction_vector, study_group, rating, visited_events_count, phone_number, telegram, avatar_url, join_date, role, telegram_id FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Gender,
		&i.DirectionVector,
		&i.StudyGroup,
		&i.Rating,
		&i.VisitedEventsCount,
		&i.PhoneNumber,
		&i.Telegram,
		&i.AvatarUrl,
		&i.JoinDate,
		&i.Role,
		&i.TelegramID,
	)
	return i, err
}

const listUsersId = `-- name: ListUsersId :many
SELECT id, full_name, gender, direction_vector, study_group, rating, visited_events_count, phone_number, telegram, avatar_url, join_date, role, telegram_id
FROM users
ORDER BY id ASC 
LIMIT $2
OFFSET $1
`

type ListUsersIdParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListUsersId(ctx context.Context, arg ListUsersIdParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersId, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Gender,
			&i.DirectionVector,
			&i.StudyGroup,
			&i.Rating,
			&i.VisitedEventsCount,
			&i.PhoneNumber,
			&i.Telegram,
			&i.AvatarUrl,
			&i.JoinDate,
			&i.Role,
			&i.TelegramID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersName = `-- name: ListUsersName :many
SELECT id, full_name, gender, direction_vector, study_group, rating, visited_events_count, phone_number, telegram, avatar_url, join_date, role, telegram_id
FROM users
ORDER BY full_name ASC 
LIMIT $2
OFFSET $1
`

type ListUsersNameParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListUsersName(ctx context.Context, arg ListUsersNameParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersName, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Gender,
			&i.DirectionVector,
			&i.StudyGroup,
			&i.Rating,
			&i.VisitedEventsCount,
			&i.PhoneNumber,
			&i.Telegram,
			&i.AvatarUrl,
			&i.JoinDate,
			&i.Role,
			&i.TelegramID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersRating = `-- name: ListUsersRating :many
SELECT id, full_name, gender, direction_vector, study_group, rating, visited_events_count, phone_number, telegram, avatar_url, join_date, role, telegram_id
FROM users
ORDER BY rating ASC 
LIMIT $2
OFFSET $1
`

type ListUsersRatingParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListUsersRating(ctx context.Context, arg ListUsersRatingParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersRating, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Gender,
			&i.DirectionVector,
			&i.StudyGroup,
			&i.Rating,
			&i.VisitedEventsCount,
			&i.PhoneNumber,
			&i.Telegram,
			&i.AvatarUrl,
			&i.JoinDate,
			&i.Role,
			&i.TelegramID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
    full_name = COALESCE($1, full_name),
    gender = COALESCE($2, gender),
    direction_vector = COALESCE($3, direction_vector),
    study_group = COALESCE($4, study_group),
    rating = COALESCE($5, rating),
    visited_events_count = COALESCE($6, visited_events_count),
    phone_number = COALESCE($7, phone_number),
    telegram = COALESCE($8, telegram),
    avatar_url = COALESCE($9, avatar_url),
    role = COALESCE($10, role)
WHERE id = $11
RETURNING id, full_name, gender, direction_vector, study_group, rating, visited_events_count, phone_number, telegram, avatar_url, join_date, role, telegram_id
`

type UpdateUserParams struct {
	FullName           pgtype.Text `json:"full_name"`
	Gender             pgtype.Text `json:"gender"`
	DirectionVector    pgtype.Text `json:"direction_vector"`
	StudyGroup         pgtype.Text `json:"study_group"`
	Rating             pgtype.Int4 `json:"rating"`
	VisitedEventsCount pgtype.Int4 `json:"visited_events_count"`
	PhoneNumber        pgtype.Text `json:"phone_number"`
	Telegram           pgtype.Text `json:"telegram"`
	AvatarUrl          pgtype.Text `json:"avatar_url"`
	Role               pgtype.Text `json:"role"`
	ID                 int32       `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FullName,
		arg.Gender,
		arg.DirectionVector,
		arg.StudyGroup,
		arg.Rating,
		arg.VisitedEventsCount,
		arg.PhoneNumber,
		arg.Telegram,
		arg.AvatarUrl,
		arg.Role,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Gender,
		&i.DirectionVector,
		&i.StudyGroup,
		&i.Rating,
		&i.VisitedEventsCount,
		&i.PhoneNumber,
		&i.Telegram,
		&i.AvatarUrl,
		&i.JoinDate,
		&i.Role,
		&i.TelegramID,
	)
	return i, err
}
