// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_events.sql

package repository

import (
	"context"
)

const getUserEventsByUserID = `-- name: GetUserEventsByUserID :many
SELECT e.id, e.event_date, e.start_time, e.end_time, e.title, e.audience, e.weight, e.participants_limit, e.participants_current, e.created_by
FROM events e
JOIN user_events ue ON ue.event_id = e.id
WHERE ue.user_id = $1
  AND (
    $2::text = 'all'
    OR (
      $2::text = 'past'
      AND (
        e.event_date < CURRENT_DATE
        OR (e.event_date = CURRENT_DATE AND COALESCE(e.end_time, TIME '23:59:59') < LOCALTIME)
      )
    )
    OR (
      $2::text = 'ongoing'
      AND (
        e.event_date = CURRENT_DATE
        AND COALESCE(e.start_time, TIME '00:00:00') <= LOCALTIME
        AND COALESCE(e.end_time, TIME '23:59:59') >= LOCALTIME
      )
    )
    OR (
      $2::text = 'upcoming'
      AND (
        e.event_date > CURRENT_DATE
        OR (e.event_date = CURRENT_DATE AND COALESCE(e.start_time, TIME '00:00:00') > LOCALTIME)
      )
    )
  )
ORDER BY e.event_date ASC, e.start_time ASC
LIMIT $4
OFFSET $3
`

type GetUserEventsByUserIDParams struct {
	UserID int32  `json:"user_id"`
	Filter string `json:"filter"`
	Offset int32  `json:"offset"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) GetUserEventsByUserID(ctx context.Context, arg GetUserEventsByUserIDParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getUserEventsByUserID,
		arg.UserID,
		arg.Filter,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.EventDate,
			&i.StartTime,
			&i.EndTime,
			&i.Title,
			&i.Audience,
			&i.Weight,
			&i.ParticipantsLimit,
			&i.ParticipantsCurrent,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerUserWithStatus = `-- name: RegisterUserWithStatus :one
WITH ev AS (
  SELECT id, event_date, participants_current, participants_limit, end_time
  FROM events
  WHERE  events.id = $1
  FOR UPDATE
),
attempt_insert AS (
  INSERT INTO user_events (user_id, event_id)
  SELECT $2, $1
  FROM ev
  WHERE (
      ev.event_date > CURRENT_DATE
      OR (
        ev.event_date = CURRENT_DATE
        AND COALESCE(ev.end_time, TIME '23:59:59') > LOCALTIME
      )
    )
    AND ev.participants_current < ev.participants_limit
  ON CONFLICT (user_id, event_id) DO NOTHING
  RETURNING event_id
),
attempt_update AS (
  UPDATE events
  SET participants_current = participants_current + 1
  WHERE id = (SELECT event_id FROM attempt_insert)
  RETURNING id
)
SELECT 
  CASE 
    WHEN NOT EXISTS (SELECT 1 FROM ev) THEN 'NOT_FOUND'
    WHEN EXISTS (SELECT 1 FROM attempt_update) THEN 'SUCCESS'
    WHEN NOT EXISTS (
      SELECT 1
      FROM ev
      WHERE (
        ev.event_date > CURRENT_DATE
        OR (
          ev.event_date = CURRENT_DATE
          AND COALESCE(ev.end_time, TIME '23:59:59') > LOCALTIME
        )
      )
    ) THEN 'REGISTRATION_CLOSED'
    WHEN NOT EXISTS (SELECT 1 FROM ev WHERE participants_current < participants_limit) THEN 'NO_VACANCY'
    WHEN NOT EXISTS (SELECT 1 FROM attempt_insert) THEN 'ALREADY_REGISTERED'
    ELSE 'UNKNOWN_ERROR'
  END AS status
`

type RegisterUserWithStatusParams struct {
	EventID int32 `json:"event_id"`
	UserID  int32 `json:"user_id"`
}

func (q *Queries) RegisterUserWithStatus(ctx context.Context, arg RegisterUserWithStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, registerUserWithStatus, arg.EventID, arg.UserID)
	var status string
	err := row.Scan(&status)
	return status, err
}
