// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_achievement.sql

package repository

import (
	"context"
)

const addUserAchievements = `-- name: AddUserAchievements :exec
INSERT INTO user_achievements (
    user_id,
    achievement_id,
    awarded_by
)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, achievement_id) DO NOTHING
`

type AddUserAchievementsParams struct {
	UserID        int32 `json:"user_id"`
	AchievementID int32 `json:"achievement_id"`
	AwardedBy     int32 `json:"awarded_by"`
}

func (q *Queries) AddUserAchievements(ctx context.Context, arg AddUserAchievementsParams) error {
	_, err := q.db.Exec(ctx, addUserAchievements, arg.UserID, arg.AchievementID, arg.AwardedBy)
	return err
}

const getUserAchievementsByUserID = `-- name: GetUserAchievementsByUserID :many
SELECT a.id, a.achivements_name, a.icon_name, a.description, a.condition_type, a.condition_value, a.created_at
FROM achievements a
JOIN user_achievements ua ON ua.achievement_id = a.id
WHERE ua.user_id = $1
ORDER BY ua.awarded_at DESC
LIMIT $3
OFFSET $2
`

type GetUserAchievementsByUserIDParams struct {
	UserID int32 `json:"user_id"`
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) GetUserAchievementsByUserID(ctx context.Context, arg GetUserAchievementsByUserIDParams) ([]Achievement, error) {
	rows, err := q.db.Query(ctx, getUserAchievementsByUserID, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Achievement{}
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(
			&i.ID,
			&i.AchivementsName,
			&i.IconName,
			&i.Description,
			&i.ConditionType,
			&i.ConditionValue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
