basePath: /
definitions:
  internal_handler.CreateUserRequest:
    properties:
      avatar_url:
        type: string
      direction_vector:
        type: string
      full_name:
        type: string
      gender:
        type: string
      phone_number:
        type: string
      rating:
        description: Если nil -> БД поставит 0
        type: integer
      study_group:
        type: string
      telegram:
        description: Обязательно (NOT NULL в БД)
        type: string
      telegram_id:
        description: UNIQUE в БД
        type: integer
      visited_events_count:
        description: Если nil -> БД поставит 0
        type: integer
    type: object
  internal_handler.UpdateUserRequest:
    properties:
      avatar_url:
        type: string
      direction_vector:
        type: string
      full_name:
        type: string
      gender:
        type: string
      phone_number:
        type: string
      rating:
        type: integer
      role:
        type: string
      study_group:
        type: string
      telegram:
        type: string
      telegram_id:
        type: integer
      visited_events_count:
        type: integer
    type: object
  pfo-vector_internal_model.ImportResult:
    properties:
      created:
        type: integer
      errors:
        items:
          $ref: '#/definitions/pfo-vector_internal_model.RowError'
        type: array
      failed:
        type: integer
      total_rows:
        type: integer
    type: object
  pfo-vector_internal_model.Pagination:
    properties:
      limit:
        type: integer
      offset:
        type: integer
      page:
        type: integer
    type: object
  pfo-vector_internal_model.RowError:
    properties:
      field:
        type: string
      reason:
        type: string
      row:
        type: integer
    type: object
  pfo-vector_internal_model.UserListResponse:
    properties:
      pagination:
        $ref: '#/definitions/pfo-vector_internal_model.Pagination'
      users:
        items:
          $ref: '#/definitions/pfo-vector_internal_model.UserResponse'
        type: array
    type: object
  pfo-vector_internal_model.UserResponse:
    properties:
      avatar_url:
        type: string
      direction_vector:
        type: string
      full_name:
        type: string
      gender:
        type: string
      id:
        type: integer
      join_date:
        type: string
      phone_number:
        type: string
      rating:
        type: integer
      role:
        type: string
      study_group:
        type: string
      telegram:
        type: string
      telegram_id:
        type: integer
      visited_events_count:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: API сервер для управления пользователями
  title: My Project API
  version: "1.0"
paths:
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Удаляет пользователя по ID
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Пользователь удален
          schema:
            $ref: '#/definitions/pfo-vector_internal_model.UserResponse'
        "404":
          description: Пользователь не найден
          schema:
            type: string
      summary: Удаление пользователя
      tags:
      - users
    get:
      consumes:
      - application/json
      description: Возвращает данные пользователя по ID
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Данные пользователя
          schema:
            $ref: '#/definitions/pfo-vector_internal_model.UserResponse'
        "404":
          description: Пользователь не найден
          schema:
            type: string
      summary: Получение пользователя
      tags:
      - users
    patch:
      consumes:
      - application/json
      description: Частично обновляет данные пользователя по ID
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: integer
      - description: Данные для обновления
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/internal_handler.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Пользователь успешно обновлен
          schema:
            $ref: '#/definitions/pfo-vector_internal_model.UserResponse'
        "400":
          description: Неверный формат запроса
          schema:
            type: string
        "404":
          description: Пользователь не найден
          schema:
            type: string
        "409":
          description: Пользователь с таким telegram_id уже существует
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Обновление пользователя
      tags:
      - users
  /users/add:
    post:
      consumes:
      - application/json
      description: Создает нового пользователя с переданными данными
      parameters:
      - description: Данные пользователя
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/internal_handler.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Пользователь успешно создан
          schema:
            $ref: '#/definitions/pfo-vector_internal_model.UserResponse'
        "400":
          description: Неверный формат запроса или валидация не пройдена
          schema:
            type: string
        "409":
          description: Пользователь с таким telegram_id уже существует
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Создание пользователя
      tags:
      - users
  /users/all:
    get:
      consumes:
      - application/json
      description: Возвращает данные пользователей по ID
      parameters:
      - default: 1
        description: Номер страницы
        in: query
        minimum: 1
        name: page
        type: integer
      - default: 20
        description: Размер страницы
        in: query
        maximum: 100
        minimum: 1
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Данные пользователей с пагинацией
          schema:
            $ref: '#/definitions/pfo-vector_internal_model.UserListResponse'
        "404":
          description: Ошибка получения списка пользователей
          schema:
            type: string
      summary: Получение всех пользователей
      tags:
      - users
  /users/all/Name:
    get:
      consumes:
      - application/json
      description: Возвращает данные пользователей по Full_name
      parameters:
      - default: 1
        description: Номер страницы
        in: query
        minimum: 1
        name: page
        type: integer
      - default: 20
        description: Размер страницы
        in: query
        maximum: 100
        minimum: 1
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Данные пользователей с пагинацией
          schema:
            $ref: '#/definitions/pfo-vector_internal_model.UserListResponse'
        "404":
          description: Ошибка получения списка пользователей
          schema:
            type: string
      summary: Получение всех пользователей
      tags:
      - users
  /users/all/Rating:
    get:
      consumes:
      - application/json
      description: Возвращает данные пользователей по Rating
      parameters:
      - default: 1
        description: Номер страницы
        in: query
        minimum: 1
        name: page
        type: integer
      - default: 20
        description: Размер страницы
        in: query
        maximum: 100
        minimum: 1
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Данные пользователей с пагинацией
          schema:
            $ref: '#/definitions/pfo-vector_internal_model.UserListResponse'
        "404":
          description: Ошибка получения списка пользователей
          schema:
            type: string
      summary: Получение всех пользователей
      tags:
      - users
  /users/import-users:
    post:
      consumes:
      - multipart/form-data
      description: Загружает Excel-файл и импортирует пользователей
      parameters:
      - description: Excel файл (.xlsx)
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Импорт завершён
          schema:
            $ref: '#/definitions/pfo-vector_internal_model.ImportResult'
        "400":
          description: Некорректный файл или данные
          schema:
            type: string
        "409":
          description: Конфликт уникальных данных
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Импорт пользователей из Excel
      tags:
      - users
schemes:
- http
swagger: "2.0"
